### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by allenwang2333** [ubc-vision/Prompting-Hard-Hardly-Prompting#5]
Did you train your model on the entire training set of COCO? Which split do you use? Current code is training on one single image.

**Comment by s-mahajan** [comment]
Hi, 
PH2P does not train the neural network. It optimizes the input embedding tokens of the text encoder used for conditioning in text-to-image diffusion models. That is, given an image, one can optimize the input embeddings using our PH2P to generate the prompt for a given image. 

In the paper, we showed results on a subset of COCO test images, where we optimize the prompt (embeddings) for each image. 
Since this is an optimization framework and not a training paradigm, we donot update the parameters of the diffusion model. 

The code works independently for each image (one prompt per image). So to extend it to generation of multiple prompts for multiple images, one can run a batch-job.

**Comment by allenwang2333** [comment]
Got it, thank you very much.

**Comment by allenwang2333** [comment]
Got it, thank you very much.
